import { ITraineeInfo } from "./src/types";

export const traineesData: ITraineeInfo[] = [
  {
    name: "ANTHONNY",
    group: "G",
    ep1: 8,
    ep2: 11,
    ep3: -1,
    company: "WAKEONE",
    id: 62,
    dob: 20040213,
    height: 174,
    hobby: "Watching movies, playing games, singing, and dancing",
    good_at: "I can sweat on my hand in no time!",
    phrase: "I will become an idol that makes you happy when you see it!!!",
  },
  {
    name: "BAK DO HA",
    group: "K",
    ep1: 27,
    ep2: 25,
    ep3: -1,
    company: "CUBE Entertainment",
    id: 12,
    dob: 20021130,
    height: 180,
    hobby: "Exercise, cook, baking, reading a novel",
    good_at: "Bass rap",
    phrase: "I’ll spend the most valuable time than others.",
  },
  {
    name: "BRIAN",
    group: "G",
    ep1: 37,
    ep2: 28,
    ep3: -1,
    company: "YUEHUA ENTERTAINMENT",
    id: 59,
    dob: 20020827,
    height: 185.7,
    hobby: "Basketball, listening to music, game",
    good_at: "Reverse thumb knuckle fold",
    phrase: "I’ll do my best. I’ll do my best.",
  },
  {
    name: "CAI JIN XIN",
    group: "G",
    ep1: 42,
    ep2: 46,
    ep3: 47,
    company: "TOPCLASS Entertainment",
    id: 80,
    dob: 20031107,
    height: 188,
    hobby:
      "Games, food trips, learning a new language, sleeping, and trying new things",
    good_at: "I'm very positive and good at mind controlling",
    phrase:
      "Let's do our best to enjoy the process rather than the result with a positive mind",
  },
  {
    name: "CHA WOONG KI",
    group: "K",
    ep1: 10,
    ep2: 17,
    ep3: -1,
    company: "WAKEONE",
    id: 42,
    dob: 20020423,
    height: 173,
    hobby: "Studying idol history, producing virtual idols, imagining…",
    good_at: "Do imagination!! Don't get knocked down♡_♡",
    phrase: "It starts now, CHA WOONG KI! Go for it! ><",
  },
  {
    name: "CHEN JIAN YU",
    group: "G",
    ep1: 28,
    ep2: 34,
    ep3: -1,
    company: "STAR ON ENTERTAINMENT",
    id: 85,
    dob: 19980901,
    height: 179,
    hobby:
      "Traveling, watching movies, driving, going to restaurants alone, playing games",
    good_at: "I’m looking for it",
    phrase:
      "I want to become a great person who proves my potential through blood and sweat.",
  },
  {
    name: "CHEN KUAN JUI",
    group: "G",
    ep1: 54,
    ep2: 30,
    ep3: -1,
    company: "Individual trainee",
    id: 81,
    dob: 20001228,
    height: 175,
    hobby: "Copy choreography, stretching, drawing, and dancing",
    good_at: "Modern dance, ballet, traditional Chinese dance",
    phrase: "I'm here for my debut, so please wait a little longer♥",
  },
  {
    name: "CHEN LIANG",
    group: "G",
    ep1: 83,
    ep2: 61,
    ep3: 57,
    company: "Individual trainee",
    id: 83,
    dob: 20000909,
    height: 185,
    hobby: "Basketball and surfing",
    good_at: "Surfing, yo-yo",
    phrase: "I won't stop again, I want to fly high~",
  },
  {
    name: "CHEN REN YOU",
    group: "G",
    ep1: 59,
    ep2: 56,
    ep3: 58,
    company: "Individual trainee",
    id: 82,
    dob: 20031217,
    height: 182,
    hobby: "Exploring food, listening to music, shopping",
    good_at: "I sing a good ballad",
    phrase: "I’ll do my best.",
  },
  {
    name: "CHEN YU GENG",
    group: "G",
    ep1: 75,
    ep2: 76,
    ep3: -1,
    company: "T.ENTER TAINMENT",
    id: 84,
    dob: 19980320,
    height: 183,
    hobby: "basketball, badminton, games, songwriting",
    good_at: "Rotate the arm 360 degrees",
    phrase: "Let's work together and have fun together on stage!",
  },
  {
    name: "CHOI JI HO",
    group: "K",
    ep1: 55,
    ep2: 58,
    ep3: -1,
    company: "FNC ENTERTAINMENT",
    id: 45,
    dob: 20040610,
    height: 182,
    hobby:
      "Basketball, soccer, table tennis, badminton, listening to music, taking a walk, and doing nothing",
    good_at: "Freestyle dance",
    phrase:
      "I'll show you everything I've prepared and I will make a stage for BOYS PLANET Legend!!",
  },
  {
    name: "CHOI SEUNG HUN",
    group: "K",
    ep1: 46,
    ep2: 52,
    ep3: 59,
    company: "OUI ENTERTAINMENT",
    id: 43,
    dob: 20080501,
    height: 171,
    hobby: "Water skiing, games, tennis",
    good_at: "Dad joke",
    phrase: "I'm not good enough, but I'll do my best.",
  },
  {
    name: "CHOI WOO JIN",
    group: "K",
    ep1: 41,
    ep2: 46,
    ep3: 52,
    company: "Redstart ENM",
    id: 44,
    dob: 20050124,
    height: 171,
    hobby: "Take a photo with a digital camera, Travel by a bicycle",
    good_at: "Take a photo",
    phrase: "I’ll do my best every time for not regretting.",
  },
  {
    name: "CONG",
    group: "G",
    ep1: 66,
    ep2: 48,
    ep3: -1,
    company: "Individual trainee",
    id: 89,
    dob: 20001208,
    height: 174,
    hobby: "Watching movies, playing games, and traveling",
    good_at: "Acting cute",
    phrase: "Debut fighting",
  },
  {
    name: "DANG HONG HAI",
    group: "G",
    ep1: 25,
    ep2: 29,
    ep3: -1,
    company: "fantagio",
    id: 52,
    dob: 20031026,
    height: 180,
    hobby: "Read the news, walk, sing",
    good_at: "Sing well without closing your eyes♥",
    phrase:
      "I will break the stage with my skills and passion, so please watch over me!",
  },
  {
    name: "DONG DONG",
    group: "G",
    ep1: 91,
    ep2: 59,
    ep3: -1,
    company: "STARDUST ENTERTAINMENT",
    id: 53,
    dob: 20001120,
    height: 175,
    hobby: "Watching movies, fashion, rap, eating delicious food",
    good_at: "low-pitched voice",
    phrase: "I'll show you the perfect look in any situation! '◡'",
  },
  {
    name: "FENG JUN LAN",
    group: "G",
    ep1: 92,
    ep2: 89,
    ep3: -1,
    company: "STARDUST ENTERTAINMENT",
    id: 93,
    dob: 19990922,
    height: 177,
    hobby: "Basketball, computer games, and eating goodies",
    good_at: "yo-yo, computer game, basketball",
    phrase: "I'm here to take over ＜BOYS PLANET＞!!!",
  },
  {
    name: "HAN SEO BIN",
    group: "K",
    ep1: 70,
    ep2: 66,
    ep3: -1,
    company: "H1GHR MUSIC",
    id: 46,
    dob: 20060702,
    height: 173.5,
    hobby:
      "Taking a walk, composing (midi), watching a movie, snacking, eating and listening to music",
    good_at: "Utmost gag skill",
    phrase: "I've done my best I’ll show you everything I've practiced...^▽^",
  },
  {
    name: "HAN YU JIN",
    group: "K",
    ep1: 3,
    ep2: 2,
    ep3: 3,
    company: "YUEHUA ENTERTAINMENT",
    id: 48,
    dob: 20070320,
    height: 177,
    hobby: "Dance, game, checking cellphone, soccer, and eating tasty thing",
    good_at: "motor system",
    phrase:
      "Please look forward to it since I’m still growing in stature and improving my skill.",
  },
  {
    name: "HAN YU SEOP",
    group: "K",
    ep1: 74,
    ep2: 71,
    ep3: -1,
    company: "JELLYFISH ENTERTAINMENT",
    id: 47,
    dob: 20040506,
    height: 173,
    hobby: "Guitar, composing, attack a melody, and take a walk",
    good_at: "Guitar",
    phrase: "I will quench your thirst with my refreshing dance and songs!!",
  },
  {
    name: "HARU",
    group: "G",
    ep1: 53,
    ep2: 64,
    ep3: -1,
    company: "Individual trainee",
    id: 94,
    dob: 20060218,
    height: 168,
    hobby: "Gag, vocal mimicry (imitation)",
    good_at: "Stitch vocal cord imitation",
    phrase: "You will only look at me",
  },
  {
    name: "HARUTO",
    group: "G",
    ep1: 39,
    ep2: 20,
    ep3: -1,
    company: "WAKEONE",
    id: 95,
    dob: 20041116,
    height: 170,
    hobby: "Study languages, observe humans, develop oatmeal recipes",
    good_at: "Wrist clap",
    phrase: "I am the seed, you are my water",
  },
  {
    name: "HIROTO",
    group: "G",
    ep1: 11,
    ep2: 15,
    ep3: -1,
    company: "RBW",
    id: 97,
    dob: 20020823,
    height: 175,
    hobby: "Game, making a rap and watching movies",
    good_at: "Eating a lot",
    phrase: "I must debut!!!!!!!",
  },
  {
    name: "HONG KEON HEE",
    group: "K",
    ep1: 87,
    ep2: 87,
    ep3: -1,
    company: "Redstart ENM",
    id: 49,
    dob: 20041115,
    height: 187,
    hobby: "Exercise, movie, asleep while watching movie, and take a walk",
    good_at: "K-pop choreography vending machine",
    phrase:
      "I’ll show you the legendary performance in every stage so that you will love me the most!!",
  },
  {
    name: "HYO",
    group: "G",
    ep1: 62,
    ep2: 90,
    ep3: -1,
    company: "Watanabe Entertainment",
    id: 96,
    dob: 20020209,
    height: 174,
    hobby: "Eating ice cream and taking pictures of it (memorial photo)",
    good_at: "Wiggling the pupils",
    phrase: "I’ll keep focusing on debut!!",
  },
  {
    name: "ICHIKA",
    group: "G",
    ep1: 58,
    ep2: 62,
    ep3: -1,
    company: "OD ENTERTAINMENT",
    id: 76,
    dob: 19921028,
    height: 182,
    hobby: "Reading and hiking",
    good_at: "Power of practice and power of action",
    phrase: "I'll show you the look of human victory!!",
  },
  {
    name: "ITSUKI",
    group: "G",
    ep1: 65,
    ep2: 81,
    ep3: -1,
    company: "MLD ENTERTAINMENT",
    id: 75,
    dob: 20060916,
    height: 171,
    hobby: "Listening to music, eating snacks",
    good_at: "Voice imitation of Spirited Away 'Kashira'",
    phrase: "I'll show you a cool image with own confidence.",
  },
  {
    name: "JANG JI HO",
    group: "K",
    ep1: 72,
    ep2: 75,
    ep3: -1,
    company: "FirstOne Entertainment",
    id: 33,
    dob: 20040810,
    height: 173,
    hobby: "Game, soccer, sleeping, checking cellphone",
    good_at: "Rolling over the bed all day long lol",
    phrase: "I’ll make you think the person, Jiho all the time.",
  },
  {
    name: "JANG YEO JUN",
    group: "K",
    ep1: 51,
    ep2: 60,
    ep3: 60,
    company: "JELLYFISH ENTERTAINMENT",
    id: 32,
    dob: 20050927,
    height: 177.5,
    hobby: "Watching videos, eating delicious food, sleeping",
    good_at: "Flexible cheek meet",
    phrase: "I will never miss this precious opportunity!",
  },
  {
    name: "JAY",
    group: "G",
    ep1: 30,
    ep2: 8,
    ep3: -1,
    company: "Fm Entertainment",
    id: 79,
    dob: 20010308,
    height: 175,
    hobby:
      "Play basketball, watch movies, write scripts, study history, and play games",
    good_at: "Playing drums with left hand",
    phrase: "I will think of BOYS PLANET as my last chance and work hard!",
  },
  {
    name: "JEON HO YOUNG",
    group: "K",
    ep1: 81,
    ep2: 80,
    ep3: -1,
    company: "OUI ENTERTAINMENT",
    id: 35,
    dob: 20041125,
    height: 178,
    hobby:
      "Reading a book, watching drama and movie, analyzing characters and circumstances",
    good_at: "Waving with eyebrows",
    phrase: "I’ll be the best!",
  },
  {
    name: "JEON WOO SEOK",
    group: "K",
    ep1: 60,
    ep2: 72,
    ep3: -1,
    company: "ALLART ENTERTAINMENT",
    id: 34,
    dob: 20030423,
    height: 173,
    hobby: "Playing basketball, walking at a park while listening to music",
    good_at: "I have fast feet",
    phrase: "Dream comes true☆",
  },
  {
    name: "JEONG I CHAN",
    group: "K",
    ep1: 52,
    ep2: 55,
    ep3: 56,
    company: "Individual trainee",
    id: 38,
    dob: 20010517,
    height: 179,
    hobby: "Watching videos, imagining a random building is mine",
    good_at: "I can make a song! ><",
    phrase: "I’ll always do my best in every time!",
  },
  {
    name: "JI YUN SEO",
    group: "K",
    ep1: 86,
    ep2: 53,
    ep3: 49,
    company: "YUEHUA ENTERTAINMENT",
    id: 41,
    dob: 20041015,
    height: 182,
    hobby:
      "Lyric writing, composing, singing, exercising, soccer game, watching movies & dramas",
    good_at: "Two-finger push-up, making a water drop sound",
    phrase:
      "Until it doesn't work, if there are no teeth, with the gums. Fire~!",
  },
  {
    name: "JUNG HO JIN",
    group: "K",
    ep1: 48,
    ep2: 68,
    ep3: -1,
    company: "Individual trainee",
    id: 39,
    dob: 20030227,
    height: 184,
    hobby:
      "Exploring restaurants, making phone calls, taking pictures, and chatting at cafes",
    good_at:
      "Girl group dance, 3 animal walks(ostrich, gorilla, giraffe), talent",
    phrase:
      "I will definitely fulfill my dream of debuting and give you lots of bright energy!",
  },
  {
    name: "JUNG MIN GYU",
    group: "K",
    ep1: 50,
    ep2: 39,
    ep3: -1,
    company: "CABIN74",
    id: 36,
    dob: 19991210,
    height: 185,
    hobby:
      "Swimming, watching movies, games, playing badminton, making Pla model, and cooking",
    good_at: "Quickly change facial expressions",
    phrase: "Do my best as today is the last day of my life!",
  },
  {
    name: "JUNG SE YUN",
    group: "K",
    ep1: 68,
    ep2: 85,
    ep3: -1,
    company: "woollim Entertainment",
    id: 37,
    dob: 20071006,
    height: 172,
    hobby:
      "Watching soccer, soccer game, watching videos, assembling blocks, watching webtoon",
    good_at:
      "Kneeling, pretending to be a praying mantis, and putting bottle caps on your eyes",
    phrase: "I’ll be the person who can resonate your heart!",
  },
  {
    name: "KEI",
    group: "G",
    ep1: 76,
    ep2: 83,
    ep3: -1,
    company: "Stardust Promotion",
    id: 87,
    dob: 20060717,
    height: 170,
    hobby:
      "Dancing, watching videos, listening to music, exercising, skateboarding",
    good_at: "Making fun face",
    phrase: "I will run with all my might to make my dream come true!!",
  },
  {
    name: "KEITA",
    group: "G",
    ep1: 14,
    ep2: 14,
    ep3: -1,
    company: "RAINCOMPANY",
    id: 88,
    dob: 20010704,
    height: 165,
    hobby: "Composition",
    good_at: "I can sleep for 3 days in a row",
    phrase: "Keita will be in charge of BOYS PLANET's K-Pop!!",
  },
  {
    name: "KIM GYU VIN",
    group: "K",
    ep1: 5,
    ep2: 4,
    ep3: -1,
    company: "YUEHUA ENTERTAINMENT",
    id: 4,
    dob: 20040830,
    height: 182,
    hobby:
      "Playing games, eating delicious food, listening to Junseo's voice imitation, Yoojin touching her face, calling Seungeon",
    good_at: "Balancing, losing rock-paper-scissors",
    phrase:
      "I worked harder than anyone else and eventually debuted in BOYS PLANET",
  },
  {
    name: "KIM JI WOONG",
    group: "K",
    ep1: 2,
    ep2: 3,
    ep3: 2,
    company: "Individual trainee",
    id: 7,
    dob: 19981214,
    height: 178,
    hobby: "Meditation, chat",
    good_at: "I can bear with hot things",
    phrase: "I’ll do my best.",
  },
  {
    name: "KIM MIN HYUK",
    group: "K",
    ep1: 90,
    ep2: 82,
    ep3: -1,
    company: "Individual trainee",
    id: 6,
    dob: 19990922,
    height: 180,
    hobby: "Games, learning new knowledge, reading, and running",
    good_at: "Eloquence",
    phrase: "I’m sure I’ll do my best than anyone!!!",
  },
  {
    name: "KIM MIN SEOUNG",
    group: "K",
    ep1: 78,
    ep2: 79,
    ep3: -1,
    company: "Redstart ENM",
    id: 5,
    dob: 20031103,
    height: 173,
    hobby:
      "Turn on the lights at home, listen to songs, draw, watch my dance & song videos",
    good_at: "Acrobatic",
    phrase:
      "I will fight with the determination to die so that I will not leave even 1mm of regret.",
  },
  {
    name: "KIM TAE RAE",
    group: "K",
    ep1: 9,
    ep2: 12,
    ep3: -1,
    company: "WAKEONE",
    id: 8,
    dob: 20020714,
    height: 174,
    hobby: "Playing the guitar and exploring restaurants",
    good_at: "Create lip triangles and add chords to songs",
    phrase: "I will advance to a debut position as high as my high treble!!",
  },
  {
    name: "KRYSTIAN",
    group: "G",
    ep1: 21,
    ep2: 23,
    ep3: -1,
    company: "Individual trainee",
    id: 90,
    dob: 20000122,
    height: 177,
    hobby:
      "Music composition, travel, health, art exhibition, music performance, etc. viewing",
    good_at: "BLACKPINK choreography master",
    phrase: "I will repay you with a shining stage.",
  },
  {
    name: "KUM JUN HYEON",
    group: "K",
    ep1: 31,
    ep2: 31,
    ep3: -1,
    company: "Redstart ENM",
    id: 3,
    dob: 20040115,
    height: 181,
    hobby: "Chat, eating",
    good_at: "I’m good at doing a diet",
    phrase: "I will do my best not to disappoint you.",
  },
  {
    name: "LEE DA EUL",
    group: "K",
    ep1: 4,
    ep2: 9,
    ep3: -1,
    company: "143inc",
    id: 22,
    dob: 20040406,
    height: 171,
    hobby:
      "Acting, ignoring Junseo's words, exercising, watching movies, eating delicious food, and sleeping",
    good_at: "Acting",
    phrase:
      "It’s your choice to fall in love with my charming point but it’s hard to get out of here.",
  },
  {
    name: "LEE DONG GUN",
    group: "K",
    ep1: 43,
    ep2: 44,
    ep3: 51,
    company: "GREAT M ENTERTAINMENT",
    id: 23,
    dob: 20050603,
    height: 179,
    hobby:
      "Stretching, watching videos, watching movies and dramas, eating delicious food, lying down, and practicing dancing and singing",
    good_at: "I’m very flexible. But I’m very powerful when I dance.",
    phrase:
      "I will work hard so that my bright smile and hopeful energy can settle in your hearts! Ha-ha",
  },
  {
    name: "LEE DONG YEOL",
    group: "K",
    ep1: 26,
    ep2: 33,
    ep3: -1,
    company: "TOPMEDIA",
    id: 24,
    dob: 19981213,
    height: 175,
    hobby:
      "Taking a walk at dawn, meeting friends, writing lyrics, and composing music",
    good_at: "Lips get bigger when you wake upor eat spicy food",
    phrase: "I’ll be the person that people want to keep watching!!",
  },
  {
    name: "LEE HOE TEAK",
    group: "K",
    ep1: 6,
    ep2: 6,
    ep3: -1,
    company: "CUBE Entertainment",
    id: 29,
    dob: 19930828,
    height: 171,
    hobby: "Making music and earning and spend money hard",
    good_at: "Play Loop Station, never give up...",
    phrase:
      "It’s a challenge but since I've started this challenge, I’ll make a good result.",
  },
  {
    name: "LEE HWAN HEE",
    group: "K",
    ep1: 38,
    ep2: 42,
    ep3: 42,
    company: "TOPMEDIA",
    id: 28,
    dob: 19980506,
    height: 173,
    hobby:
      "Watching drama movies and webtoons at home, and imagining star creators",
    good_at: "Blocking nostril one side without using my hands…♡",
    phrase: "I will show you Hwanhee who is good at having fun♡",
  },
  {
    name: "LEE JEONG HYEON",
    group: "K",
    ep1: 35,
    ep2: 43,
    ep3: 41,
    company: "WAKEONE",
    id: 27,
    dob: 20020911,
    height: 183,
    hobby: "Cube matching, wrap making",
    good_at: "Solve cube fast",
    phrase:
      "I’ll show all the things that I’ve got such as skills or charming!",
  },
  {
    name: "LEE SEUNG HWAN",
    group: "K",
    ep1: 13,
    ep2: 16,
    ep3: -1,
    company: "Individual trainee",
    id: 25,
    dob: 20000520,
    height: 178,
    hobby: "games, snacks, conversation",
    good_at:
      "Shameless (saying anything well), eating well, taking good care of those around you (My friends told me♥)",
    phrase: "Even if I can't fly high, I'll fly far!",
  },
  {
    name: "LEE YE DAM",
    group: "K",
    ep1: 45,
    ep2: 47,
    ep3: 46,
    company: "LM ENTERTAINMENT",
    id: 26,
    dob: 20030119,
    height: 167,
    hobby: "Exercise, playing instrument, games, and sleeping",
    good_at: "Limbo (not flexible ^^)",
    phrase:
      "I can see my future over there. I’ll keep going higher and higher until I can get that future!",
  },
  {
    name: "LIM JUN SEO",
    group: "K",
    ep1: 19,
    ep2: 21,
    ep3: -1,
    company: "143inc",
    id: 30,
    dob: 20050501,
    height: 178,
    hobby: "Sleeping at home, rolling all over all day long, talking to Daeul",
    good_at: "Moving ears",
    phrase: "＜BOYS PLANET＞, wait and see. LIM JUN SEO is going.",
  },
  {
    name: "LIN SHI YUAN",
    group: "G",
    ep1: 89,
    ep2: 91,
    ep3: -1,
    company: "Individual trainee",
    id: 56,
    dob: 19981009,
    height: 183,
    hobby: "Travel and game",
    good_at: "Acrobatic",
    phrase: "I will definitely enter the lucky number '7'.",
  },
  {
    name: "MA JING XIANG",
    group: "G",
    ep1: 16,
    ep2: 27,
    ep3: -1,
    company: "Individual trainee",
    id: 57,
    dob: 20040216,
    height: 188,
    hobby: "Exploring tasty food",
    good_at: "Model walking, pose, Woo Kimyung pose",
    phrase:
      "If you practice a lot, you won't be nervous. To the top JING XIANG. Please remember my name!",
  },
  {
    name: "MIN",
    group: "G",
    ep1: 80,
    ep2: 65,
    ep3: -1,
    company: "WAKEONE",
    id: 58,
    dob: 20000315,
    height: 176,
    hobby: "Drawing, cooking, watching horror movies, traveling alone outside",
    good_at: "Sing whistle, hand wave",
    phrase: "Let’s go MIN",
  },
  {
    name: "MUN JONG HYUN",
    group: "K",
    ep1: 24,
    ep2: 35,
    ep3: -1,
    company: "WAKEONE",
    id: 9,
    dob: 20050331,
    height: 182,
    hobby:
      "Listening to songs, singing songs, eating delicious food, and reading novels",
    good_at: "Imperfect absolute pitch",
    phrase:
      "I will show you the tension of the other world that no one has been able to handle yet.",
  },
  {
    name: "NA KAMDEN",
    group: "G",
    ep1: 82,
    ep2: 37,
    ep3: 40,
    company: "FNC ENTERTAINMENT",
    id: 51,
    dob: 20010609,
    height: 182,
    hobby: "Cooking, shopping, making phone calls, soccer, watching videos",
    good_at: "Make water droplets using your hands and mouth",
    phrase: "I will enjoy it without regret!",
  },
  {
    name: "NICE",
    group: "G",
    ep1: 71,
    ep2: 63,
    ep3: -1,
    company: "Individual trainee",
    id: 50,
    dob: 20000827,
    height: 180,
    hobby:
      "Watching movies, playing games, drawing, practicing dancing, and making short videos",
    good_at: "Making monkey noises",
    phrase: "I really want to debut in Korea.",
  },
  {
    name: "OH SUNG MIN",
    group: "K",
    ep1: 17,
    ep2: 24,
    ep3: -1,
    company: "WAKEONE",
    id: 19,
    dob: 20010825,
    height: 181,
    hobby: "MBTI overimmersion, food tour",
    good_at: "The practice room, the god of organizing the dorm!!",
    phrase: "We will show you a more grown image!!",
  },
  {
    name: "OLLIE",
    group: "G",
    ep1: 23,
    ep2: 18,
    ep3: -1,
    company: "YUEHUA ENTERTAINMENT",
    id: 66,
    dob: 20060401,
    height: 180.2,
    hobby: "Watching movies, listening to music, and playing various sports",
    good_at: "rap tone",
    phrase: "I will warm your heart like hot choco.",
  },
  {
    name: "OSUKE",
    group: "G",
    ep1: 63,
    ep2: 69,
    ep3: -1,
    company: "Individual trainee",
    id: 64,
    dob: 20030515,
    height: 164,
    hobby: "Watching movies, playing with cats, and archery",
    good_at: "Shrink my thumb",
    phrase:
      "I will not forget to thank you and will spare no effort! Go for it!!",
  },
  {
    name: "OUJU",
    group: "G",
    ep1: 67,
    ep2: 78,
    ep3: -1,
    company: "HYPER RHYTHM",
    id: 65,
    dob: 20040404,
    height: 171,
    hobby: "Watch games, anime, and cartoons",
    good_at: "Doraemon Toongtoongi Vocal Imitation",
    phrase: "I’m OUJU! Please look me cute~!",
  },
  {
    name: "PARK GUN WOOK",
    group: "K",
    ep1: 15,
    ep2: 10,
    ep3: -1,
    company: "JELLYFISH ENTERTAINMENT",
    id: 10,
    dob: 20050110,
    height: 183,
    hobby:
      "Showing off my forearms, watching soccer, eating chocolate, playing games, and walking",
    good_at: "High pitch",
    phrase: "I will work hard until I can be proud of the name PARK GUN WOOK.",
  },
  {
    name: "PARK GWAN YOUNG",
    group: "K",
    ep1: 61,
    ep2: 92,
    ep3: -1,
    company: "Individual trainee",
    id: 11,
    dob: 20010109,
    height: 170,
    hobby:
      "Playing games, finding and listening to new songs, reading movie reviews, exploring restaurants, and collecting character props",
    good_at: "Jumping high",
    phrase: "I’ll be working the hardest as this time is the last opportunity.",
  },
  {
    name: "PARK HAN BIN",
    group: "K",
    ep1: 34,
    ep2: 36,
    ep3: -1,
    company: "WAKEONE",
    id: 15,
    dob: 20020301,
    height: 175,
    hobby: "Reading essay books, walking the Han River, watching movies ^^",
    good_at: "I always smile^^",
    phrase: "I’ll invest everything to BOYS PLANET!!",
  },
  {
    name: "PARK HYUN BEEN",
    group: "K",
    ep1: 40,
    ep2: 50,
    ep3: 54,
    company: "JELLYFISH ENTERTAINMENT",
    id: 16,
    dob: 20050411,
    height: 179,
    hobby: "Cassette, LP, CD collection, watching movie and cartoon/anime",
    good_at: "Lots of personal skills",
    phrase:
      "I will work really hard! Me, PARK HYUN BEEN No one can stop me! Come on!",
  },
  {
    name: "PARK JI HOO",
    group: "K",
    ep1: 47,
    ep2: 49,
    ep3: 48,
    company: "H1GHR MUSIC",
    id: 14,
    dob: 20060714,
    height: 175,
    hobby:
      "Games, midi, basketball, soccer, exercise, sleeping at home, songwriting",
    good_at: "Dimple",
    phrase: "We will show you everything as much as we have prepared.",
  },
  {
    name: "PARK MIN SEOK",
    group: "K",
    ep1: 64,
    ep2: 84,
    ep3: -1,
    company: "WAKEONE",
    id: 13,
    dob: 20020727,
    height: 183,
    hobby: "Cooking, exploring restaurants ^^",
    good_at: "Doing nothing, eating a lot, soft voice",
    phrase: "We will write a new history in ＜BOYS PLANET＞ and K-POP!!!",
  },
  {
    name: "QIU SHENG YANG",
    group: "G",
    ep1: 88,
    ep2: 70,
    ep3: -1,
    company: "TPOP Entertainment",
    id: 86,
    dob: 20010816,
    height: 177,
    hobby: "Badminton, dancing, sleeping, and drinking black tea",
    good_at: "Create double eyelids",
    phrase: "I will make a miracle myself!!!!",
  },
  {
    name: "RICKY",
    group: "G",
    ep1: 12,
    ep2: 13,
    ep3: -1,
    company: "YUEHUA ENTERTAINMENT",
    id: 55,
    dob: 20040520,
    height: 183.9,
    hobby:
      "Find delicious food in shopping, producing, basketball, and delivery apps",
    good_at: "Playing basketball, good sense, no special talent",
    phrase:
      "I am confident in singing, dancing, and rapping. keep your eyes on me, Ricky will show you his own style!",
  },
  {
    name: "RIKU",
    group: "G",
    ep1: 93,
    ep2: 88,
    ep3: -1,
    company: "Individual trainee",
    id: 54,
    dob: 20041002,
    height: 181,
    hobby: "Exercising, playing together, shopping",
    good_at: "Limbo",
    phrase: "I will charm you with a lovely figure.",
  },
  {
    name: "SEO WON",
    group: "K",
    ep1: 18,
    ep2: 22,
    ep3: -1,
    company: "FirstOne Entertainment",
    id: 17,
    dob: 20001218,
    height: 170,
    hobby:
      "Calligraphy, coloring, makeup, thinking about fans, walking without thinking, and eye shopping",
    good_at: "Good at makeup and calligraphy",
    phrase:
      "SEO WON is coming!! Everyone must be nervous!!! I will work hard, so please look at me pretty~^▽^♡♡♡♡",
  },
  {
    name: "SEOK MATTHEW",
    group: "G",
    ep1: 32,
    ep2: 5,
    ep3: -1,
    company: "MNH Entertainment",
    id: 60,
    dob: 20020528,
    height: 170,
    hobby:
      "Exercising, playing games, taking a walk, visiting restaurants alone or with friends",
    good_at: "I can fall asleep anywhere in 2 minutes",
    phrase: "I will do it without regret.",
  },
  {
    name: "SUNG HAN BIN",
    group: "K",
    ep1: 1,
    ep2: 1,
    ep3: 1,
    company: "STUDIO GL1DE",
    id: 18,
    dob: 20010613,
    height: 179,
    hobby: "Writing, reading, and choreography",
    good_at: "I'm good at using my arms when dancing",
    phrase: "All in. I'll bet my all.",
  },
  {
    name: "TAKUTO",
    group: "G",
    ep1: 20,
    ep2: 19,
    ep3: -1,
    company: "YY ENTERTAINMENT",
    id: 91,
    dob: 20071113,
    height: 165,
    hobby: "Reading, cycling and traveling in nature",
    good_at: "Make the belly full",
    phrase: "I don't know yet, but I want to do my best while looking around!",
  },
  {
    name: "TOUI",
    group: "G",
    ep1: 85,
    ep2: 93,
    ep3: -1,
    company: "FNC ENTERTAINMENT JAPAN",
    id: 92,
    dob: 20030827,
    height: 181,
    hobby: "Games, fishing, eating delicious food, and singing",
    good_at: "Shaolin Temple",
    phrase: "We will show you a performance that will impress you.",
  },
  {
    name: "WANG YAN HONG",
    group: "G",
    ep1: 79,
    ep2: 77,
    ep3: -1,
    company: "ASE",
    id: 67,
    dob: 19981120,
    height: 177,
    hobby: "Playing games, watching cartoons, and watching movies",
    good_at: "Design clothes, play the clarinet",
    phrase: "I will continue to grow with solid basics!",
  },
  {
    name: "WANG ZI HAO",
    group: "G",
    ep1: 29,
    ep2: 38,
    ep3: -1,
    company: "CHROMOSOME",
    id: 68,
    dob: 20010306,
    height: 178,
    hobby: "Yoga, listening to music, shopping, playing games",
    good_at: "Crump",
    phrase: "I am ZI HAO who is not afraid of challenges.",
  },
  {
    name: "WEN YE CHEN",
    group: "G",
    ep1: 56,
    ep2: 57,
    ep3: 53,
    company: "Individual trainee",
    id: 70,
    dob: 20000915,
    height: 183,
    hobby:
      "Exploring restaurants, listening to music, reading, watching movies and dramas",
    good_at: "musical, acting, and ear movement",
    phrase: "I will become a star with a shining passion.",
  },
  {
    name: "WINNIE",
    group: "G",
    ep1: 77,
    ep2: 73,
    ep3: -1,
    company: "FirstOne Entertainment",
    id: 71,
    dob: 19981118,
    height: 171,
    hobby:
      "Watching movies, playing games, drawing with AI, soccer, badminton, singing practice, writing lyrics, learning new skills, and food trips",
    good_at: "Touching the nose with the tongue, and freestyle (dance)",
    phrase: "We will show you strength in kindness!",
  },
  {
    name: "WUMUTI",
    group: "G",
    ep1: 49,
    ep2: 51,
    ep3: 50,
    company: "JPark&Company",
    id: 69,
    dob: 19990707,
    height: 175,
    hobby: "Drawing, cleaning, bowling, and walking",
    good_at: "Drawing, Timbre",
    phrase: "I tried the hardest in my 23 years of life!",
  },
  {
    name: "XUAN HAO",
    group: "G",
    ep1: 33,
    ep2: 41,
    ep3: 44,
    company: "Beijng Stardyehot Entertainment",
    id: 61,
    dob: 19951108,
    height: 180,
    hobby: "Movies, late night snacks, dances, and songs",
    good_at: "Video editing, leading as a leader",
    phrase: "I will try to become a center of confidence!!!",
  },
  {
    name: "YANG JUN",
    group: "G",
    ep1: 84,
    ep2: 74,
    ep3: -1,
    company: "ASE",
    id: 63,
    dob: 19990507,
    height: 176,
    hobby: "Exercising, visiting restaurants, and watching movies",
    good_at: "Boxing and table tennis",
    phrase: "I will do my best not to be afraid of mistakes.",
  },
  {
    name: "YOO SEUNG EON",
    group: "K",
    ep1: 44,
    ep2: 26,
    ep3: -1,
    company: "YUEHUA ENTERTAINMENT",
    id: 20,
    dob: 20040102,
    height: 179,
    hobby:
      "Composition, listening to songs, exercising (soccer, basketball, table tennis, bowling), eating snacks, and playing games",
    good_at: "Doraemon vocal mimicry",
    phrase: "I will do my best to be in the debut group of BOYS PLANET.",
  },
  {
    name: "YOON JONG WOO",
    group: "K",
    ep1: 73,
    ep2: 67,
    ep3: 45,
    company: "Individual trainee",
    id: 21,
    dob: 20000612,
    height: 175,
    hobby: "Practice games, exercise, walks, drives, and dances",
    good_at:
      "Swimming (former athlete), skating (former athlete), choreography creation",
    phrase: "The important thing is an unbreakable heart",
  },
  {
    name: "YUKI",
    group: "G",
    ep1: 36,
    ep2: 40,
    ep3: 43,
    company: "Individual trainee",
    id: 72,
    dob: 20011224,
    height: 172,
    hobby: "Video production, screenplay, novel writing",
    good_at: "Finger snap",
    phrase: "元気 やる気 由晖!! I will work hard with passion!",
  },
  {
    name: "YUTAKA",
    group: "G",
    ep1: 57,
    ep2: 54,
    ep3: 55,
    company: "Individual trainee",
    id: 73,
    dob: 19990313,
    height: 171,
    hobby: "Collecting figures",
    good_at: "Splits",
    phrase: "I will make people around the world laugh with my voice.",
  },
  {
    name: "YUTO",
    group: "G",
    ep1: 69,
    ep2: 86,
    ep3: -1,
    company: "Individual trainee",
    id: 74,
    dob: 20041214,
    height: 170,
    hobby: "Dancing, eating ice cream, and watching musical animated movies",
    good_at: "Eating food quickly",
    phrase: 'To others it\'s pow"pow"pow", only to you, bang"bang"bang"!',
  },
  {
    name: "ZHANG HAO",
    group: "G",
    ep1: 7,
    ep2: 7,
    ep3: -1,
    company: "YUEHUA ENTERTAINMENT",
    id: 78,
    dob: 20000725,
    height: 180.5,
    hobby: "Food tour, swimming, walking, and travel",
    good_at: "Violin, pitch",
    phrase: "Please look forward to the passion of music genius Zhang Hao!",
  },
  {
    name: "ZHANG SHUAI BO",
    group: "G",
    ep1: 22,
    ep2: 32,
    ep3: -1,
    company: "WELL Entertainment",
    id: 77,
    dob: 20020702,
    height: 185,
    hobby: "Talking, sleeping, and dazing",
    good_at: "Frog jump",
    phrase: "Go for it",
  },
];
